Added Lesson 17
selivanov-d/train_manager pull request #4
Opened 2016-09-29 19:18 UTC by selivanov-d

2016-10-01 00:32 UTC, psylone requested changes

2016-10-01 00:32 UTC, psylone commented on app/controllers/tickets_controller.rb
>    def destroy
Хорошо бы проверять наличие пользователя, иначе можно не логинясь удалить билет.

2016-10-01 00:32 UTC, psylone commented on app/controllers/tickets_controller.rb
>      @ticket = Ticket.find(params[:id])
Здесь лучше `current_user.tickets.find(params[:id])`.

2016-10-01 00:32 UTC, psylone commented on app/views/users/show.html.erb
> +<%= link_to 'Редактировать', edit_admin_user_path(@user) %> |
Может быть разный набор параметров которые можно редактировать непосредственно пользователю и администратору. Поэтому здесь лучше направлять запросы на `UsersController`.

2016-10-01 00:32 UTC, psylone commented on app/controllers/tickets_controller.rb
> +    current_user.tickets << @ticket
Можно сразу: `current_user.tickets.create!(ticket_params)`.

2016-10-02 15:48 UTC, selivanov-d commented on app/controllers/tickets_controller.rb
>    def destroy
Поправил.

2016-10-02 15:51 UTC, selivanov-d commented on app/controllers/tickets_controller.rb
>      @ticket = Ticket.find(params[:id])
Да, наверное так безопаснее. Поправил.

2016-10-02 15:55 UTC, selivanov-d commented on app/controllers/tickets_controller.rb
> +    current_user.tickets << @ticket
Запомню. Но тут у меня всё равно создаётся инстанс-переменная `@ticket`, чтобы её потом передать в метод `show`, плюс мой вариант как-то понятнее что ли. :) Так что, оставлю как есть.

2016-10-02 15:58 UTC, selivanov-d commented on app/views/users/show.html.erb
> +<%= link_to 'Редактировать', edit_admin_user_path(@user) %> |
Неправильно прописал путь к экшену. Нужно было направлять на редактирование данных пользователя не в админке, а в его собственном профиле.
Поправил.

2016-10-03 20:24 UTC, psylone commented on app/controllers/tickets_controller.rb
> +    current_user.tickets << @ticket
Всё же обычно это делают так: `@ticket = current_user.tickets.create!(params)`.

2016-10-03 20:26 UTC, psylone approved these changes

2016-10-05 12:00 UTC, merged